// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-fqv3G3Hjci4H7z_m9cEqZbHwZsKALFo',
    appId: '1:432336520162:web:c89d8613af0e84d6c96fbb',
    messagingSenderId: '432336520162',
    projectId: 'calendar-scheduler-372c2',
    authDomain: 'calendar-scheduler-372c2.firebaseapp.com',
    storageBucket: 'calendar-scheduler-372c2.appspot.com',
    measurementId: 'G-S6BW1Q53Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuLNJoY3pZ0_ZIA_nBL_iX8AMnfJVp62E',
    appId: '1:432336520162:android:bcdcb2572804b91cc96fbb',
    messagingSenderId: '432336520162',
    projectId: 'calendar-scheduler-372c2',
    storageBucket: 'calendar-scheduler-372c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAQlGClkWGk1M3s9_hK-OYNI3HOOBRPx8',
    appId: '1:432336520162:ios:d4010cca6373b789c96fbb',
    messagingSenderId: '432336520162',
    projectId: 'calendar-scheduler-372c2',
    storageBucket: 'calendar-scheduler-372c2.appspot.com',
    iosBundleId: 'com.example.calendarScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAQlGClkWGk1M3s9_hK-OYNI3HOOBRPx8',
    appId: '1:432336520162:ios:857cacffe14e5532c96fbb',
    messagingSenderId: '432336520162',
    projectId: 'calendar-scheduler-372c2',
    storageBucket: 'calendar-scheduler-372c2.appspot.com',
    iosBundleId: 'com.example.calendarScheduler.RunnerTests',
  );
}
